I prevously installed **Pandas** using the command: "pip install pandas" via *Anaconda prompt*

In [19]:
pwd

'C:\\Users\\user\\Documents\\Project\\code'

In [20]:
import pandas as pd

In [21]:
# reading the csv data file with url:
df = pd.read_csv("https://osf.io/7gvz9//download") 

In [22]:
df.head()
# head() prints the first five rows by default; alternatively, one can set the number of rows as follows: head(#_of_rows

pricestr     area       subarea                      name  condition  \
0    $4990  chicago  chicago city  2007 Toyota Camry Hybrid       good   
1   $10625  chicago  chicago city  2009 Toyota Camry Hybrid        NaN   
2   $14850  chicago  chicago city       2015 Toyota_ Camry_  excellent   
3   $15630  chicago  chicago city         2016 TOYOTA CAMRY        NaN   
4     $850  chicago  chicago city         1993 toyota camry       good   

     cylinders drive    fuel  odometer paintcolor  ... dealer  price  \
0  4 cylinders   fwd     gas   11.6236       grey  ...      1   4990   
1  4 cylinders   fwd  hybrid    4.3702       grey  ...      1  10625   
2        other   NaN     gas    3.5721        NaN  ...      1  14850   
3          NaN   fwd     gas    1.3152        NaN  ...      1  15630   
4  6 cylinders   fwd     gas   18.7000        red  ...      0    850   

    lnprice  year  age  lnodometer  LE  XLE  SE  Hybrid  
0  8.515191  2007   11    2.453038   0    0   0       1  
1  9.270965  2009    9    1.474809   0    0   0       1  
2  9.605755  2015    3    1.273154   0    0   0       0  
3  9.656947  2016    2    0.273989   0    0   0       0  
4  6.745236  1993   25    2.928524   0    0   0       0  

[5 rows x 23 columns]

In [23]:
# generating a list from the column "area" to apply 'word_count' function to it later on
area_list = df['area'].tolist()

In [24]:
df['area_list'] = area_list

In [25]:
df.head(10).area_list

0    chicago
1    chicago
2    chicago
3    chicago
4    chicago
5    chicago
6    chicago
7    chicago
8    chicago
9    chicago
Name: area_list, dtype: object

In [26]:
# creating a function 'word_count':
def word_count(abc):
    counter = {}
    for word in abc:
        if word in counter:
            # print('Increment:', word)
            counter[word] = counter[word] + 1
        else:
            # print('First time:', word)
            counter[word] = 1
        # print(counter)
    return counter

In [27]:
word_count(area_list)

{'chicago': 327, 'los angeles': 222}

```There are 327 used cars from Chicago and 222 from Los Angeles in the dataset```

In [28]:
for name, values in df.iteritems():
    print('{name}: {value}'.format(name=name, value=values[0]))

pricestr: $4990
area: chicago
subarea: chicago city
name: 2007 Toyota Camry Hybrid
condition: good
cylinders: 4 cylinders
drive: fwd
fuel: gas
odometer: 11.6236
paintcolor: grey
size: nan
transmission: automatic
type: sedan
dealer: 1
price: 4990
lnprice: 8.5151911
year: 2007
age: 11
lnodometer: 2.4530375
LE: 0
XLE: 0
SE: 0
Hybrid: 1
area_list: chicago


In [29]:
for ind, column in enumerate(df.columns):
    print(ind, column)

0 pricestr
1 area
2 subarea
3 name
4 condition
5 cylinders
6 drive
7 fuel
8 odometer
9 paintcolor
10 size
11 transmission
12 type
13 dealer
14 price
15 lnprice
16 year
17 age
18 lnodometer
19 LE
20 XLE
21 SE
22 Hybrid
23 area_list


In [30]:
age_list = df['age'].tolist()

In [31]:
old_new = ['new' if n < 8 else 'old' for n in age_list] 

In [32]:
df['old_new'] = old_new

In [33]:
df.head().old_new

0    old
1    old
2    new
3    new
4    old
Name: old_new, dtype: object

In [34]:
df.to_csv('../data/used-cars.csv')